-- WidgetKit/Supabase smoke test table.
-- Run this manually in the Supabase SQL editor for a development project.
--
-- SECURITY WARNING:
-- The anon read/update policies below are TEMPORARY DEVELOPMENT-ONLY policies
-- for proving that the iOS WidgetKit extension can fetch and PATCH Supabase
-- directly over HTTPS. They are unsafe for production because anyone with the
-- anon/publishable key can read and update every row in public.widget_test.
-- Replace them with a proper authenticated per-user RLS design before release.

create table if not exists public.widget_test (
  id bigint generated by default as identity primary key,
  message text not null,
  acknowledged boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists widget_test_set_updated_at on public.widget_test;
create trigger widget_test_set_updated_at
before update on public.widget_test
for each row
execute function public.set_updated_at();

alter table public.widget_test enable row level security;

insert into public.widget_test (message, acknowledged)
select 'Hello from Supabase', false
where not exists (select 1 from public.widget_test);

-- TEMPORARY DEVELOPMENT-ONLY: unsafe public read policy for widget smoke tests.
drop policy if exists "widget_test_dev_anon_read" on public.widget_test;
create policy "widget_test_dev_anon_read"
on public.widget_test
for select
to anon
using (true);

-- TEMPORARY DEVELOPMENT-ONLY: unsafe public update policy for widget smoke tests.
drop policy if exists "widget_test_dev_anon_update" on public.widget_test;
create policy "widget_test_dev_anon_update"
on public.widget_test
for update
to anon
using (true)
with check (true);
